FROM nginx:1.19-alpine

COPY --from=kremen-web-dev:latest /usr/src/app/dist /var/www/html/kremen.dev
COPY --from=kremen-web-transport:latest /usr/src/app/dist /var/www/html/transport.kremen.dev
COPY --from=kremen-web-deputies:latest /usr/src/app/dist /var/www/html/deputat.kremen.dev
COPY --from=kremen-web-equipment:latest /usr/src/app/dist /var/www/html/equipment.kremen.dev

COPY conf /etc/nginx/conf.d
